version: '2'
networks:
 prodnetwork:
  driver: bridge
services:
 jenkins:
  container_name: jenkins
  image: jenkins
  ports:
   - "8080:8080"
  networks:
   - prodnetwork
  depends_on:
   - sonar
  environment:
   - SONAR_PORT=9000
   - SONAR_DB_PORT=5432
    
 sonar:
  container_name: sonarqube
  image: sonarqube
  ports:
   - "9000:9000"
   - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar

 sonardb:
  networks:
   - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
